### ISSUE TITLE
Error on excution

### ISSUE THREAD

**Issue by pabloiea1995** [tpluscode/rdfine#93]
Hello, it is throwing me this error, looks like is something related with package.json on @rdf-esm

curl http://usefulinc.com/ns/doap -H accept:application/rdf+xml -H | \
  rdfine-gen \
  --format application/rdf+xml \
  --prefix foaf
curl: option -H: requires parameter
curl: try 'curl --help' or 'curl --manual' for more information
internal/modules/cjs/loader.js:1172
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/lib/node_modules/@rdfine/generator/node_modules/@rdf-esm/namespace/index.js
require() of ES modules is not supported.
require() of /usr/local/lib/node_modules/@rdfine/generator/node_modules/@rdf-esm/namespace/index.js from /usr/local/lib/node_modules/@rdfine/generator/node_modules/@tpluscode/rdf-ns-builders/vocabularies/as.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/local/lib/node_modules/@rdfine/generator/node_modules/@rdf-esm/namespace/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@rdfine/generator/node_modules/@tpluscode/rdf-ns-builders/vocabularies/as.js:6:37)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by tpluscode** [comment]
Hello @pabloiea1995. You're right, the `@rdf-esm` packages are dual packages, with ES modules exported by default. Good support for modules is only well supported in more recent versions of node (v13+ or v12 with flag).

Looks like you would need to switch to at least node 13. What version are you using?

**Comment by pabloiea1995** [comment]
I am currently using 12.16.1, ill switch to v13 an try it again. Thanks!

**Comment by pabloiea1995** [comment]
Now, with node 13 the error is the following.  Not really sure if I am doing something wrong, but I was just following the documentation... :S

curl http://usefulinc.com/ns/doap -H accept:application/rdf+xml -H | \
  rdfine-gen \
  --format application/rdf+xml \
  --prefix foaf
curl: option -H: requires parameter
curl: try 'curl --help' or 'curl --manual' for more information
internal/modules/cjs/loader.js:458
  throw e;
  ^

Error: Package exports for '/usr/local/lib/node_modules/@rdfine/generator/node_modules/@zazuko/rdf-vocabularies' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:455:13)
    at resolveExports (internal/modules/cjs/loader.js:388:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:487:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:782:27)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@rdfine/generator/lib/index.js:38:28)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10) {
  code: 'MODULE_NOT_FOUND'
}

**Comment by pabloiea1995** [comment]
> Right, similar problem with es modules. Looks like I should also increase the version of `@zazuko/rdf-vocabularies` dependency. Please update to at least `^2020.6.29`

current version is ^2020.8.17

**Comment by tpluscode** [comment]
You likely have multiple versions installed. Notice the nested `node_modules/@zazuko/rdf-vocabularies` inside the generator's installation.

Please update `@rdfine/generator` to 0.4.3 (should be up in a few minutes)

**Comment by tpluscode** [comment]
hey @pabloiea1995. I noticed later today that misconfigured automation prevented the npm publish. No matter however, because to have DOAP generated there were a bunch of fixes needed for the generator as well as generating more vocabularies (`@rdfine/generator` assumes that imported vocabs have their own `@rdfine/*` packages)

Thus, I will be soon publishing new version of the generator as well as DOAP + its dependencies: FOAF, SIOC and WGS as their own generated packages.

I'll let you know when `@rdfine/doap` is published and would like to you to give it a go and tell me if and what tweaks are needed to make it useful. Especially to correct property types which are generated as RDF/JS terms or where multiple values are desired for a property

**Comment by pabloiea1995** [comment]
Ok! Ill be waiting for your updates. Thank you!

**Comment by tpluscode** [comment]
Sorry for the delay. Please try [@rdfine/doap](https://npm.im/@rdfine/doap)
